version: "3.8"

services:
  nodejs:
    build: .
    depends_on:
      - mongodb
    restart: always
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
  mongodb:
    image: mongo:5.0.2
    restart: always
    env_file: ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - mongodb:/data/db
  

volumes:
  mongodb: